# Generated by Django 4.2.7 on 2023-11-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas_investigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='iconos/', verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='iconos/', verbose_name='imagen')),
            ],
        ),
    ]
