# Generated by Django 4.2.7 on 2024-01-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imacuna', '0002_alter_lineas_investigacion_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prinom', models.CharField(max_length=50, verbose_name='primer_nombre')),
                ('segnom', models.CharField(max_length=45, null=True, verbose_name='segundo_nombre')),
                ('priape', models.CharField(max_length=50, verbose_name='primer_nombre')),
                ('segape', models.CharField(max_length=45, null=True, verbose_name='segundo_nombre')),
                ('correo', models.CharField(max_length=200, verbose_name='correo')),
                ('contrasena', models.CharField(max_length=120, verbose_name='contraseña')),
            ],
        ),
    ]
