# Generated by Django 4.2.7 on 2024-01-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imacuna', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rol',
            new_name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
